### ISSUE TITLE
scope & closures 第6题有误

### ISSUE THREAD

**Issue by Chersquwn** [shfshanyue/blog#2]
```javascript
for (var i = 0; i < 10; i++) {
  setTimeout(function () {
    console.log(i);
  }, i * 1000)
}
```

> 1s 之后连续输出 10 个 10。因为没有块级作用域，可以把 var 改成 let，也可以给 setTimeout 包装一层 IIFE。

此处不是1s之后连续输出10个10，而是先输出10，之后大约9秒内每隔1s输出1个10

**Comment by shfshanyue** [comment]
谢谢，想成间隔为 1000 了，我还是改回 1000 吧。
