### ISSUE TITLE
在ssh_config里禁用密码登录无意义

### ISSUE THREAD

**Issue by imba-tjd** [shfshanyue/blog#40]
<https://shanyue.tech/op/init.html#禁用密码登录>

`ssh_config`是客户端配置。改`sshd_config`才对

**Comment by shfshanyue** [comment]
恩，我好像写的就是 `sshd_config`

```
# 编辑服务器端的 /etc/ssh/sshd_config
# 禁用密码登录
Host *
  PasswordAuthentication no
```

**Comment by imba-tjd** [comment]
https://github.com/shfshanyue/op-note/commit/bbcfa684e85459cdb1d76e446d3d59b5163738da#diff-24f14e8bc2db2f8447e489c9e0327d48L91
