### ISSUE TITLE
IEEE754中，二进制小数点右移应该是乘以2的N次方，而不是10的N次方

### ISSUE THREAD

**Issue by xulonc** [shfshanyue/blog#76]
https://devtool.tech/double-type
IEEE754中，二进制小数点右移应该是乘以2的N次方，而不是10的N次方
![image](https://user-images.githubusercontent.com/77042549/200127541-de67b7ba-9106-48df-a0a3-6ad122b1f7ff.png)

**Comment by shfshanyue** [comment]
在二进制中，`10` 就是 2
